
CREATE TABLE ranking_list (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    video_id BIGINT UNSIGNED NOT NULL COMMENT '视频ID',
    rank_type TINYINT NOT NULL COMMENT '榜单类型: 1-日榜 2-周榜',
    score BIGINT DEFAULT 0 COMMENT '综合得分',
    create_by BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_video_ranktype (video_id, rank_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='视频排行榜表';